### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by Breeze773** [alirawashdeh/wunderlist-alexa#1]
Hello,

I'm looking forward to using this skill!
I am having problems getting started.  I get the below error when trying to start npm.

```
> alexia-hello-world@1.0.0 start /home/breeze/work/wunderlist-alexa
> node index

/home/breeze/work/wunderlist-alexa/index.js:53
app.intent('AddItem', AddItemIntents, (slots, attrs, data) => {
                                                           ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

```
Here is the info in npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@2.15.11
3 info using node@v0.12.18
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart alexia-hello-world@1.0.0
7 info start alexia-hello-world@1.0.0
8 verbose unsafe-perm in lifecycle true
9 info alexia-hello-world@1.0.0 Failed to exec start script
10 verbose stack Error: alexia-hello-world@1.0.0 start: `node index`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1019:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1091:5)
11 verbose pkgid alexia-hello-world@1.0.0
12 verbose cwd /home/breeze/work/wunderlist-alexa
13 error Linux 3.13.0-92-generic
14 error argv "/usr/bin/node" "/usr/bin/npm" "start"
15 error node v0.12.18
16 error npm  v2.15.11
17 error code ELIFECYCLE
18 error alexia-hello-world@1.0.0 start: `node index`
18 error Exit status 1
19 error Failed at the alexia-hello-world@1.0.0 start script 'node index'.
19 error This is most likely a problem with the alexia-hello-world package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node index
19 error You can get information on how to open an issue for this project with:
19 error     npm bugs alexia-hello-world
19 error Or if that isn't available, you can get their info via:
19 error
19 error     npm owner ls alexia-hello-world
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

**Comment by alirawashdeh** [comment]
Hi, it seems to have a problem with the => syntax - which is part of ECMAScript6. This only works in more recent versions of node (http://node.green/). Could you try upgrading node?

```node --version```

I've tested with node v6.3.0

**Comment by Breeze773** [comment]
That worked.  Thanks for the quick reply.  Moving on to deploying it to Heroku
